name: brew pr-pull

on:
  workflow_call:
    inputs:
      pull-request-number:
        required: true
        type: number
      origin-branch-to-delete:
        required: false
        type: string
    secrets:
      GITHUB_ACCESS_TOKEN:
        required: true

jobs:
  pr-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up Git
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
        run: brew pr-pull --debug --tap=${{ github.repository }} ${{ inputs.pull-request-number }}

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          branch: main

      - name: Delete branch
        if: ${{ inputs.origin-branch-to-delete != '' }}
        run: git push --delete origin ${{ inputs.origin-branch-to-delete }}
