name: brew test-bot

on:
  workflow_call:
    inputs:
      os-type:
        required: true
        type: string
      os-gen:
        required: true
        type: string
      os-arch:
        required: true
        type: string
      ec2-launch-template:
        required: true
        type: string
    secrets:
      GITHUB_ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      RUNNER_TOKEN:
        required: true

jobs:
  start-runner:
    name: Start self-hosted AWS EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: fac/ec2-github-runner@670c9074237211ea48c905ebf14b884e0c9e74b7
        with:
          mode: start
          github-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          ec2-launch-template: ${{ inputs.ec2-launch-template }}
          aws-resource-tags: >
            [
              {"Key": "runner-token", "Value": "${{ secrets.RUNNER_TOKEN }}"},
              {"Key": "runner-name", "Value": "homebrew-${{ inputs.os-type }}-${{ inputs.os-gen }}-${{ inputs.os-arch }}-ec2"},
              {"Key": "runner-labels", "Value": "self-hosted,ec2,homebrew,${{ inputs.os-type }},${{ inputs.os-gen }},${{ inputs.os-arch }}"}
            ]

  test-bot:
    name: Run Homebrew's test-bot
    runs-on: [self-hosted, homebrew, '${{ inputs.os-type }}', '${{ inputs.os-gen }}', '${{ inputs.os-arch }}']
    needs: start-runner
    timeout-minutes: 600

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'

  stop-runner:
    name: Stop self-hosted AWS EC2 runner
    if: ${{ always() && (needs.start-runner.outputs.label != '' || needs.start-runner.outputs.ec2-instance-id != '') }}
    runs-on: ubuntu-latest
    needs:
      - start-runner
      - test-bot

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 runner
        uses: fac/ec2-github-runner@670c9074237211ea48c905ebf14b884e0c9e74b7
        with:
          mode: stop
          github-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
