name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    runs-on: macos-latest
    timeout-minutes: 600
    strategy:
      matrix:
        include:
          - os-type: macos
            os-gen: monterey
            os-arch: arm64

          - os-type: macos
            os-gen: monterey
            os-arch: x64

    steps:
      - name: Prepare workspace
        run: rm -rf "${{ github.workspace }}/*"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # - name: Cache Homebrew Bundler RubyGems
      #   id: cache
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ steps.set-up-homebrew.outputs.gems-path }}
      #     key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
      #     restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      # - name: Adjust Git configuration
      #   run: |
      #     git lfs uninstall || true
      #     git lfs uninstall --local || true
      #     git lfs uninstall --system || true
      #     git config --global submodule.recurse 1
      #     git config --global fetch.parallel 10
      #     git config --global submodule.fetchJobs 10

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
